Retrieve probabilities from detections.
prabindh/darknet pull request #68
Opened 2018-09-14 08:45 UTC by ooobelix

2018-09-28 12:08 UTC, prabindh requested changes
@ooobelix  Could you please respond to the comments ? Thanks

2018-09-28 12:08 UTC, prabindh commented on arapaho/test.cpp
> +                        sprintf(str, "%s: %f", labels[objId].c_str(), probs[objId]);
Can we use snprintf (secure variants) instead please ?

2018-09-28 12:08 UTC, prabindh commented on arapaho/test.cpp
> +                        DPRINTF("Label:%s, Probabilty: %f\n\n", labels[objId].c_str(), probAsString);
Where is probAsString declared ?

2018-09-28 12:35 UTC, ooobelix commented on arapaho/test.cpp
> +                        DPRINTF("Label:%s, Probabilty: %f\n\n", labels[objId].c_str(), probAsString);
you are right, sorry! It's "char str[200]; ", fixed in the same branch!

2019-04-10 09:08 UTC, ooobelix commented on arapaho/test.cpp
> +                        sprintf(str, "%s: %f", labels[objId].c_str(), probs[objId]);
Fixed, thanks for the review

2019-04-11 09:06 UTC, prabindh approved these changes

2019-04-11 09:06 UTC, merged